version: '2.2'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - goWechat

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - goWechat
  go_wechat_server:
    image: abang/go_wechat_server:compose
    # 以下这种方式为从dockerfile来打包启动
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    container_name: go_wechat_server_compose
    ports:
      - 10086:10086
    environment:
      - GO_ENV=compose
    networks:
      - goWechat
    restart: always

networks:
  goWechat:
    driver: bridge