name: wechatSever
port: 80
common:
    pg:
        dialect: postgres
        host: postgres
        port: 5432
        username: postgres
        password: postgres
        database: postgres
        max: 100
        idle: 10
    redis:
        db: 0
        password: ""
        addr: redis:6379
    es:
        db: elasticsearch
        port: 9200
wechat:
    appid: wx05c79371924706da
    secrect: c3a0ba476d2466ff9b53de50ce3f433d
    token: abangReadBook